(deftheme antoine
  "Created 2014-08-08.")

(custom-theme-set-variables
 'antoine
 '(add-to-list (quote auto-mode-alist))
 '(ansi-color-names-vector ["#2e3436" "#a40000" "#4e9a06" "#c4a000" "#204a87" "#5c3566" "#729fcf" "#eeeeec"])
 '(browse-url-browser-function (quote browse-url-generic))
 '(browse-url-firefox-program "firefox")
 '(browse-url-generic-program "firefox")
 '(buffers-menu-show-status t)
 '(case-fold-search nil)
 '(compilation-read-command nil)
 '(compilation-window-height 20)
 '(custom-safe-themes (quote ("ce79400f46bd76bebeba655465f9eadf60c477bd671cbcd091fe871d58002a88" "f5e9f66da69f504cb61aacedeb8284d8f38f2e6f835fd658cac5f0ad5d924549" default)))
 '(fill-column 80)
 '(flymake-allowed-file-name-masks (quote (("\\.\\(?:c\\(?:pp\\|xx\\|\\+\\+\\)?\\|CC\\)\\'" flymake-simple-make-init) ("\\.xml\\'" flymake-xml-init) ("\\.html?\\'" flymake-xml-init) ("\\.cs\\'" flymake-simple-make-init) ("\\.p[ml]\\'" flymake-perl-init) ("\\.php[345]?\\'" flymake-php-init) ("\\.h\\|\\.hpp\\'" flymake-master-make-header-init flymake-master-cleanup) ("\\.java\\'" flymake-simple-make-java-init flymake-simple-java-cleanup) ("[0-9]+\\.tex\\'" flymake-master-tex-init flymake-master-cleanup) ("\\.tex\\'" flymake-simple-tex-init) ("\\.scala\\'" flymake-simple-make-init) ("\\.idl\\'" flymake-simple-make-init))))
 '(flymake-log-level -1)
 '(font-lock-maximum-decoration t)
 '(indicate-empty-lines t)
 '(inhibit-local-menu-bar-menus nil)
 '(inhibit-startup-screen t)
 '(safe-local-variable-values (quote ((eval checkdoc-minor-mode 1))))
 '(tooltip-mode nil)
 '(ido-mode t)
 '(fringe-mode (quote (nil . 0))))

(custom-theme-set-faces
 'antoine
 '(cursor ((t (:background "grey40"))))
 '(diff-added ((t (:inherit diff-changed :foreground "green3"))))
 '(diff-changed ((nil nil)))
 '(diff-file-header ((((class color) (min-colors 88) (background dark)) (:underline "yellow" :weight bold))))
 '(diff-header ((((class color) (min-colors 88) (background dark)) (:height 1.15))))
 '(diff-hunk-header ((t (:foreground "purple3"))))
 '(diff-index ((t nil)))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(diff-nonexistent ((t nil)))
 '(diff-refine-added ((t (:inherit diff-added-face :underline t))))
 '(diff-refine-change ((((class color) (min-colors 88) (background dark)) nil)))
 '(diff-refine-removed ((t (:inherit diff-removed-face :underline t))))
 '(diff-removed ((t (:inherit diff-changed :foreground "red3"))))
 '(flymake-errline ((((class color) (background dark)) (:underline "Firebrick4"))))
 '(flymake-warnline ((((class color) (background dark)) (:underline "yellow"))))
 '(highlight ((nil (:background "orange"))))
 '(hl-line ((t (:background "gray10"))))
 '(hl-paren-face ((t (:weight bold))))
 '(hl-sexp-face ((t (:background "dark orange"))))
 '(menu ((t (:overline nil))))
 '(rainbow-delimiters-depth-1-face ((((background light)) (:foreground "red"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "dark red"))))
 '(rainbow-delimiters-unmatched-face ((((background light)) (:foreground "gold"))))
 '(semantic-tag-boundary-face ((((class color) (background dark)) (:overline "orange4"))))
 '(vertical-border ((nil (:background "black" :foreground "black")))))

(provide-theme 'antoine)
